openapi: 3.0.0
info:
  title: API des Transactions
  version: 1.0.0
  description: API pour gérer les transactions des utilisateurs.
servers:
  - url: http://localhost:3001/api/v1
paths:
  /transactions:
    get:
      summary: Récupérer toutes les transactions pour le mois en cours
      description: Retourne les transactions de l'utilisateur pour le mois en cours, groupées par compte.
      parameters:
        - name: userId
          in: query
          required: true
          description: ID de l'utilisateur pour lequel récupérer les transactions.
          schema:
            type: string
      responses:
        '200':
          description: Liste des transactions récupérées avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        date:
                          type: string
                          format: date
                        description:
                          type: string
                        amount:
                          type: string
                        balance:
                          type: string
        '404':
          description: Aucun utilisateur trouvé avec l'ID spécifié.

  /transactions/{id}:
    get:
      summary: Récupérer les détails d'une transaction spécifique
      description: Retourne les détails d'une transaction donnée par son ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la transaction à récupérer.
          schema:
            type: string
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  date:
                    type: string
                    format: date
                  description:
                    type: string
                  amount:
                    type: string
                  balance:
                    type: string
        '404':
          description: Transaction non trouvée avec l'ID spécifié.

    put:
      summary: Modifier une transaction existante
      description: Met à jour les informations d'une transaction donnée par son ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la transaction à mettre à jour.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                amount:
                  type: string
      responses:
        '200':
          description: Transaction mise à jour avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        '404':
          description: Transaction non trouvée avec l'ID spécifié.
        '400':
          description: Requête invalide. Vérifiez les paramètres fournis.

    delete:
      summary: Supprimer une transaction
      description: Supprime une transaction donnée par son ID. (Cette opération est à discuter, car mentionné qu'on ne supprimera pas de transaction.)
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la transaction à supprimer.
          schema:
            type: string
      responses:
        '204':
          description: Transaction supprimée avec succès.
        '404':
          description: Transaction non trouvée avec l'ID spécifié.