openapi: 3.0.0
info:
  title: API des Transactions
  version: 1.0.0
  description: API pour gérer les transactions des utilisateurs.
servers:
  - url: http://localhost:3001/api/v1
paths:
  /transactions/{userId}:  # Le chemin doit commencer par "/"
    get:
      summary: Récupérer toutes les transactions pour le mois en cours
      description: Retourne les transactions de l'utilisateur pour le mois en cours, groupées par compte.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID de l'utilisateur pour lequel récupérer les transactions.
          schema:
            type: string
      responses:
        '200':
          description: Liste des transactions récupérées avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        date:
                          type: string
                          format: date
                        description:
                          type: string
                        amount:
                          type: string
                        balance:
                          type: string
                        transactionDetails:
                          type: object
                          properties:
                            transactionType:
                              type: string
                            category:
                              type: string
                            notes:
                              type: string
        '404':
          description: Aucun utilisateur trouvé avec l'ID spécifié.

  /transactions/{userId}/{id}/transactionDetails:  # Le chemin doit commencer par "/"
    get:
      summary: Récupérer les détails d'une transaction spécifique
      description: Retourne uniquement les détails de la transaction, incluant le type de transaction, la catégorie et la note.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID de l'utilisateur.
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID de la transaction à récupérer.
          schema:
            type: string
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionDetails: 
                    type: object
                    properties:
                      transactionType:
                        type: string
                      category:
                        type: string
                      notes:
                        type: string
        '404':
          description: Transaction non trouvée avec l'ID spécifié.
        '400':
          description: Requête invalide. Vérifiez les paramètres fournis.

    put:
      summary: Modifier les details d'une transaction existante
      description: Met à jour les informations d'une transaction donnée par son ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID de l'utilisateur.
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID de la transaction à mettre à jour.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                note:
                  type: string
                  description: Note à modifier pour la transaction.
      responses:
        '200':
          description: Transaction mise à jour avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        '404':
          description: Transaction non trouvée avec l'ID spécifié.
        '400':
          description: Requête invalide. Vérifiez les paramètres fournis.

    post:
      summary: Ajouter une information aux détails d'une transaction
      description: Ajoute une information aux détails d'une transaction existante.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID de l'utilisateur.
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID de la transaction à mettre à jour.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                detail1 rajouté:
                  type: string
                  description: Note à ajouter à la transaction.
                detail2 rajouté:
                  type: string
                  description: Catégorie à ajouter à la transaction.
      responses:
        '200':
          description: Informations ajoutées avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: ID de la transaction modifiée.
        '404':
          description: Transaction non trouvée avec l'ID spécifié.
        '400':
          description: Requête invalide. Vérifiez les paramètres fournis.

    delete:
      summary: Supprimer des informations d'une transaction
      description: Supprime certaines informations d'une transaction donnée par son ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID de l'utilisateur.
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID de la transaction dont les informations doivent être supprimées.
          schema:
            type: string
      responses:
        '204':
          description: Informations de la transaction supprimées avec succès.
        '404':
          description: Transaction non trouvée avec l'ID spécifié.
        '400':
          description: Requête invalide. Vérifiez les paramètres fournis.
